# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/design_1_toplevel_0_2.xci
# IP: The module: 'design_1_toplevel_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] -quiet

# IP: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/aee_rom/aee_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aee_rom || ORIG_REF_NAME==aee_rom} -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_ooc.xdc

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/aee_rom/aee_rom_ooc.xdc

# IP: D:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/design_1_toplevel_0_2.xci
# IP: The module: 'design_1_toplevel_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] -quiet

# IP: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/aee_rom/aee_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aee_rom || ORIG_REF_NAME==aee_rom} -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_generator || ORIG_REF_NAME==clock_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/clock_generator/clock_generator_ooc.xdc

# XDC: d:/VDesign/RISCV32I/RISCV32I.srcs/sources_1/bd/design_1/ip/design_1_toplevel_0_2/src/aee_rom/aee_rom_ooc.xdc
